/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_clear_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_clear_result$schema = z.object({
  'ok': z.boolean(),
  'path': z.string(),
  'saved': z.boolean().optional(),
  'error': z.string(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_parameter_1$schema = z.string()
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_result$schema = z.object({
  'ok': z.boolean(),
  'path': z.string(),
  'saved': z.boolean().optional(),
  'error': z.string(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_read_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_read_result$schema = z.object({
  'ok': z.boolean(),
  'path': z.string(),
  'raw': z.string(),
  'parsed': z.object({
  'found': z.boolean(),
  'sections': z.array(z.object({
  'name': z.string(),
  'order': z.number(),
  'enabled': z.boolean(),
  'text': z.string(),
})),
  'history': z.array(z.object({
  'user': z.string(),
  'assistant': z.string(),
})),
  'includeSubagents': z.boolean(),
  'historyMode': z.string(),
  'seedMode': z.string(),
}),
  'error': z.string(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_parameter_1$schema = z.object({
  'found': z.boolean(),
  'sections': z.array(z.object({
  'name': z.string(),
  'order': z.number(),
  'enabled': z.boolean(),
  'text': z.string(),
})),
  'history': z.array(z.object({
  'user': z.string(),
  'assistant': z.string(),
})),
  'includeSubagents': z.boolean(),
  'historyMode': z.string(),
  'seedMode': z.string(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_result$schema = z.object({
  'ok': z.boolean(),
  'path': z.string(),
  'saved': z.boolean().optional(),
  'error': z.string(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_preview_assemble_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_preview_assemble_result$schema = z.object({
  'sections': z.array(z.object({
  'name': z.string(),
  'text': z.string(),
  'order': z.number(),
})),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_clear_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_clear_result$schema = z.object({
  'requests': z.array(z.object({
  'id': z.number(),
  'time': z.number(),
  'model': z.string(),
  'provider': z.string(),
  'system': z.string(),
  'messages': z.array(z.object({
  'role': z.string(),
  'text': z.string(),
})),
})),
  'paused': z.boolean(),
  'dockVisible': z.boolean(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_list_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_list_result$schema = z.object({
  'requests': z.array(z.object({
  'id': z.number(),
  'time': z.number(),
  'model': z.string(),
  'provider': z.string(),
  'system': z.string(),
  'messages': z.array(z.object({
  'role': z.string(),
  'text': z.string(),
})),
})),
  'paused': z.boolean(),
  'dockVisible': z.boolean(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_parameter_1$schema = z.boolean()
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_result$schema = z.object({
  'requests': z.array(z.object({
  'id': z.number(),
  'time': z.number(),
  'model': z.string(),
  'provider': z.string(),
  'system': z.string(),
  'messages': z.array(z.object({
  'role': z.string(),
  'text': z.string(),
})),
})),
  'paused': z.boolean(),
  'dockVisible': z.boolean(),
})
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_parameter_1$schema = z.boolean()
const _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_result$schema = z.object({
  'requests': z.array(z.object({
  'id': z.number(),
  'time': z.number(),
  'model': z.string(),
  'provider': z.string(),
  'system': z.string(),
  'messages': z.array(z.object({
  'role': z.string(),
  'text': z.string(),
})),
})),
  'paused': z.boolean(),
  'dockVisible': z.boolean(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-custom-first-control-prompt',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/config-clear',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'config-clear',
      implementation: 'configClear',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_clear_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelWriteResult',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_clear_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":294,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/config-raw-import',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'config-raw-import',
      implementation: 'configRawImport',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_parameter_0$schema,
          },
        },
        {
          name: 'raw',
          wire: 'raw',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/config-raw-import:raw',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelWriteResult',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_raw_import_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":304,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/config-read',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'config-read',
      implementation: 'configRead',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_read_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelConfigReadResult',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_read_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":279,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/config-write',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'config-write',
      implementation: 'configWrite',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_parameter_0$schema,
          },
        },
        {
          name: 'config',
          wire: 'config',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelConfigView',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelWriteResult',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_config_write_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":286,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/preview-assemble',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'preview-assemble',
      implementation: 'previewAssemble',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_preview_assemble_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelAssembleResult',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_preview_assemble_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":346,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/requests-clear',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'requests-clear',
      implementation: 'requestsClear',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_clear_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelRequestsView',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_clear_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":329,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/requests-list',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'requests-list',
      implementation: 'requestsList',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelRequestsView',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_list_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":314,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/requests-set-paused',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'requests-set-paused',
      implementation: 'requestsSetPaused',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_parameter_0$schema,
          },
        },
        {
          name: 'paused',
          wire: 'paused',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/requests-set-paused:paused',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelRequestsView',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_requests_set_paused_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":321,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/ui-set-dock-visible',
      service: 'custom-first-control-prompt-panel',
      namespace: 'custom-first-control-prompt-panel',
      method: 'ui-set-dock-visible',
      implementation: 'uiSetDockVisible',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_parameter_0$schema,
          },
        },
        {
          name: 'visible',
          wire: 'visible',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt#custom-first-control-prompt-panel/ui-set-dock-visible:visible',
            schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-custom-first-control-prompt/client#PanelRequestsView',
        schema: _deepseek_ai_dsh_custom_first_control_prompt_custom_first_control_prompt_panel_ui_set_dock_visible_result$schema,
      },
      sourceLocation: {"file":"packages/context/custom-first-control-prompt/src/panel.ts","line":338,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "Contribute durable seed events before a session is prepared. Listeners receive the identity and creation metadata of the session about to be created and the seed accumulated so far; call `next()` to reach downstream contributions plus the caller-supplied seed, then return the complete seed list. Contributed events must form balanced, fully closed turns contiguously numbered from the accumulated seed.",
        "summary": "Contribute durable seed events before a session is prepared.",
        "tags": [
          {
            "name": "param",
            "argument": "payload.sessionId",
            "comment": "- identity of the session being created.",
            "text": "@param payload.sessionId - identity of the session being created.\r\n     *"
          },
          {
            "name": "param",
            "argument": "payload.meta",
            "comment": "- creation metadata; mirrors `CreateAgentOptions.meta` (cwd, fork lineage, origin, delegation budget, preset).",
            "text": "@param payload.meta - creation metadata; mirrors `CreateAgentOptions.meta`\r\n     *   (cwd, fork lineage, origin, delegation budget, preset).\r\n     *"
          },
          {
            "name": "param",
            "argument": "next",
            "comment": "- downstream contributions plus the caller-supplied seed.",
            "text": "@param next - downstream contributions plus the caller-supplied seed.\r\n     *"
          },
          {
            "name": "returns",
            "comment": "the complete seed event list the factory passes to the session boundary.",
            "text": "@returns the complete seed event list the factory passes to the session boundary.\r\n     *"
          },
          {
            "name": "mode",
            "comment": "waterfall",
            "text": "@mode waterfall"
          }
        ],
        "jsDoc": "/**\r\n * Contribute durable seed events before a session is prepared. Listeners\r\n * receive the identity and creation metadata of the session about to be\r\n * created and the seed accumulated so far; call `next()` to reach\r\n * downstream contributions plus the caller-supplied seed, then return the\r\n * complete seed list. Contributed events must form balanced, fully closed\r\n * turns contiguously numbered from the accumulated seed.\r\n * @param payload.sessionId - identity of the session being created.\r\n * @param payload.meta - creation metadata; mirrors `CreateAgentOptions.meta`\r\n *   (cwd, fork lineage, origin, delegation budget, preset).\r\n * @param next - downstream contributions plus the caller-supplied seed.\r\n * @returns the complete seed event list the factory passes to the session boundary.\r\n * @mode waterfall\r\n */",
        "name": "agent-loop/session-seed",
        "mode": "waterfall",
        "signature": "'agent-loop/session-seed'(payload: { sessionId: SessionId; meta: Readonly<{ cwd?: string; parentSession?: SessionId; seedLength?: number; origin?: 'subagent'; delegationDepth?: number; agentPreset?: string; }> | undefined; }, next: () => Promise<readonly SessionEvent[]>): Promise<readonly SessionEvent[]>"
      }
    ],
    "objects": []
  },
}
