/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PanelAssembleResult, PanelConfigReadResult, PanelConfigView, PanelRequestsView, PanelWriteResult } from '@wm-coders/dsh-custom-first-control-prompt/typert-client'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$637573746f6d2d66697273742d636f6e74726f6c2d70726f6d70742d70616e656c {
    'config-clear': (agentId: SessionId) => Promise<RemoteResult<PanelWriteResult>>
    'config-raw-import': (agentId: SessionId, raw: string) => Promise<RemoteResult<PanelWriteResult>>
    'config-read': (agentId: SessionId) => Promise<RemoteResult<PanelConfigReadResult>>
    'config-write': (agentId: SessionId, config: PanelConfigView) => Promise<RemoteResult<PanelWriteResult>>
    'preview-assemble': (agentId: SessionId) => Promise<RemoteResult<PanelAssembleResult>>
    'requests-clear': (agentId: SessionId) => Promise<RemoteResult<PanelRequestsView>>
    'requests-list': (agentId: SessionId) => Promise<RemoteResult<PanelRequestsView>>
    'requests-set-paused': (agentId: SessionId, paused: boolean) => Promise<RemoteResult<PanelRequestsView>>
    'ui-set-dock-visible': (agentId: SessionId, visible: boolean) => Promise<RemoteResult<PanelRequestsView>>
  }
  interface TypertRemoteMap {
    'custom-first-control-prompt-panel/config-clear': (agentId: SessionId) => Promise<RemoteResult<PanelWriteResult>>
    'custom-first-control-prompt-panel/config-raw-import': (agentId: SessionId, raw: string) => Promise<RemoteResult<PanelWriteResult>>
    'custom-first-control-prompt-panel/config-read': (agentId: SessionId) => Promise<RemoteResult<PanelConfigReadResult>>
    'custom-first-control-prompt-panel/config-write': (agentId: SessionId, config: PanelConfigView) => Promise<RemoteResult<PanelWriteResult>>
    'custom-first-control-prompt-panel/preview-assemble': (agentId: SessionId) => Promise<RemoteResult<PanelAssembleResult>>
    'custom-first-control-prompt-panel/requests-clear': (agentId: SessionId) => Promise<RemoteResult<PanelRequestsView>>
    'custom-first-control-prompt-panel/requests-list': (agentId: SessionId) => Promise<RemoteResult<PanelRequestsView>>
    'custom-first-control-prompt-panel/requests-set-paused': (agentId: SessionId, paused: boolean) => Promise<RemoteResult<PanelRequestsView>>
    'custom-first-control-prompt-panel/ui-set-dock-visible': (agentId: SessionId, visible: boolean) => Promise<RemoteResult<PanelRequestsView>>
  }
  interface TypertRemoteNamespaceMap {
    'custom-first-control-prompt-panel': TypertRemoteNamespace$637573746f6d2d66697273742d636f6e74726f6c2d70726f6d70742d70616e656c
  }
  interface TypertRemoteScopeMap {
    'agent:custom-first-control-prompt-panel/config-clear': () => Promise<RemoteResult<PanelWriteResult>>
    'agent:custom-first-control-prompt-panel/config-raw-import': (raw: string) => Promise<RemoteResult<PanelWriteResult>>
    'agent:custom-first-control-prompt-panel/config-read': () => Promise<RemoteResult<PanelConfigReadResult>>
    'agent:custom-first-control-prompt-panel/config-write': (config: PanelConfigView) => Promise<RemoteResult<PanelWriteResult>>
    'agent:custom-first-control-prompt-panel/preview-assemble': () => Promise<RemoteResult<PanelAssembleResult>>
    'agent:custom-first-control-prompt-panel/requests-clear': () => Promise<RemoteResult<PanelRequestsView>>
    'agent:custom-first-control-prompt-panel/requests-list': () => Promise<RemoteResult<PanelRequestsView>>
    'agent:custom-first-control-prompt-panel/requests-set-paused': (paused: boolean) => Promise<RemoteResult<PanelRequestsView>>
    'agent:custom-first-control-prompt-panel/ui-set-dock-visible': (visible: boolean) => Promise<RemoteResult<PanelRequestsView>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
